<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Assets\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="..\THIRD_PARTY_NOTICES.md" Link="THIRD_PARTY_NOTICES.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.Production.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <!--Condition below is needed to remove AvaloniaUI.DiagnosticsSupport package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tempest.REST\Tempest.REST.csproj" />
        <ProjectReference Include="..\Tempest.WebSocket\Tempest.WebSocket.csproj" />
    </ItemGroup>
</Project>
